name: Test build

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm install

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/restore-cache

      - name: Run lint
        run: npm run lint

  format-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/restore-cache

      - name: Run format check
        run: npm run format:check
